### ISSUE TITLE
padronização dos nomes da função de cada desafio

### ISSUE THREAD

**Issue by emerson-oliveira** [he4rt/he4rtoberfest-2023#17]
Pegando como exemplo o[ codewars ](https://www.codewars.com/)onde os desafios tem apenas um escopo vazio onde os usuários vão inserir o seu código.

Pegando o exemplo da tarefa 0 no js poderia ser algo como:

```js

function main() {
  
}
```

Teste 
```js

describe('Main', function() {
  it('should return "Hello World"', function() {
    expect(main()).toEqual('Hello World');
  });
});
````

**Comment by lanjoni** [comment]
Muito obrigado pela issue! Perfeito, poderíamos padronizar, mas, por agora, as verificações estão sendo feitas via I/O! O nosso bot para validação apenas verifica o retorno printado para facilitar a verificação de múltiplas linguagens de programação.

Claro que a sugestão é mais do que excelente e pensamos em padronizar e criar uma ferramenta completa para o próximo ano, tendo em vista que este ano o pessoal aparenta estar muito animado, porém, para agora não seria propriamente necessário!

Vou deixar anotado a issue aqui e pode ter certeza que vamos trabalhar nisso! Muito obrigado desde já!
